version: '2'

services:
  nginx:
    image: nginx:1.17.5
    ports:
      - 80:80
    volumes:
      - ./project:/usr/share/nginx/html:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
      - mysql
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./project:/usr/share/nginx/html:rw
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=1234